server:
  port: 8084

spring:
  application:
    name: admin-service
    
  cloud:
    config:
      uri: http://config-server:8888
      fail-fast: false  
      retry:
        initial-interval: 3000
        max-attempts: 10
        multiplier: 1.5
        
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://mysql:3306/admin_db}
    username: root
    password: smit

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:redis}
      port: 6379
  cache:
    type: redis
    redis:
      time-to-live: 60000
      cache-null-values: false

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://discovery-server:8761/eureka}
  instance:
    prefer-ip-address: true
    hostname: ${EUREKA_INSTANCE_HOSTNAME:admin-service}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${MANAGEMENT_ZIPKIN_TRACING_ENDPOINT:http://zipkin:9411/api/v2/spans}

logging:
  file:
    name: logs/admin-service.log

