server:
  port: 8761

spring:
  application:
    name: discovery-server

  cloud:
    config:
      uri: http://config-server:8888
      fail-fast: false   
      retry:
        initial-interval: 3000
        max-attempts: 10
        multiplier: 1.5

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${MANAGEMENT_ZIPKIN_TRACING_ENDPOINT:http://zipkin:9411/api/v2/spans}

logging:
  file:
    name: logs/discovery-server.log

